name: Output information
on: 
  workflow_dispatch:
    inputs:
      stage:
        type: choice
        description: Select stage
        options:
          - dev
          - int
          - prod

jobs:
  info:
    runs-on: windows-latest
    steps:
      - name: Output GitHub context
        run: echo "${{ toJson(github) }}"
