name: Output information
on: 
  workflow_dispatch:
    inputs:
      -dev
      -int
      -prod

jobs:
  info:
    runs-on: windows-latest
    steps:
      - name: Output GitHub context
        run: echo "${{ toJSON(github) }}"
