name: react-workflow

on: push

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Specify the version of Node.js you want to use

      - name: Install dependencies
        run: npm ci  # Install dependencies using npm ci

      - name: Run tests
        run: npm test  # Run tests using npm test
